<h3>Modify Genre</h3>
<form class="mb-3" action="updateGenre" method="POST">
    <input type="hidden" name="id" value="<?= $genre->id ?>">
    <label for="name" class="form-label">
        <h4>Name</h4>
    </label>
    <input type="text" class="form-control" name="name" value="<?= $genre->name ?>" required>
    <label for="image_url" class="form-label">
        <h4>URL de la imagen</h4>
    </label>
    <input type="url" class="form-control" name="image_url" value="<?= $genre->image_url ?>" required>
    <button type="submit" class="btn btn-primary mt-2">Confirm modification</button>
</form>