<section class="col-md-4">
    <form class="mb-3" action="addGenre" method="POST">
        <h3>Add new genre</h3>
        <label for="name" class="form-label mt-1 mb-auto">
            <h4>Name</h4>
        </label>
        <input type="text" class="form-control" required name="name" id="name" placeholder="Action">

        <label for="image_url" class="form-label mt-1 mb-auto">
            <h4>URL de la imagen</h4>
        </label>
        <input type="url" class="form-control" required name="image_url" id="image_url" placeholder="URL">
        <button type="submit" class="btn btn-success mt-2">Add genre</button>
    </form>
</section>
