<?php require 'templates/layout/header.phtml' ?>

<section class="container mt-4 d-flex flex-column vh-100">
    <article class="header">
        <h1>Genre management</h1>
            <!-- Formulario de modificacion -->
            <?php if (isset($genre)): ?>
            <?php require 'formGenresDBModify.phtml' ?>

        <?php else: ?>
            <div class="row">
                <!-- Columna para el formulario -->
                <?php require 'formGenresDB.phtml' ?>

                <!-- Columna para la lista de generos -->
                <?php require 'listGenresDB.phtml' ?>
            </div>
        <?php endif; ?>
    </article>
</section>
<?php require 'templates/layout/footer.phtml' ?>
