<div class="col-md-8">
    <div class="genres mt-3">
        <h3>Genre List</h3>
        <ul class="list-group mb-4 w-100">
            <?php foreach ($genres as $genre): ?>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <p class="m-0"><?= htmlspecialchars($genre->name) ?></p>
                    <span>
                        <a href="modifyGenre/<?= $genre->id ?>" type="button"
                            class='btn btn-warning btn-sm m-1'>Modify</button>
                            <a href="removeGenre/<?= $genre->id ?>" type="button"
                                class='btn btn-danger btn-sm m-1'>Delete</a>
                    </span>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>