<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<div class="vh-100 w-50 m-auto d-flex justify-content-center align-items-center shadow bg-body-tertiary rounded">
    <form class="d-flex flex-column w-50" method='post' action='login'>
        <div class='form-group'>
            <label for='text'>User</label>
            <input type='text' class='form-control' id='username' name='username' required>
        </div>
        <div class='form-group'>
            <label for='password'>Password</label>
            <input type='password' class='form-control' id='password' name='password' required>
        </div>
        <button type='submit' class='btn btn-primary w-25 mt-2 m-auto'>Login</button>
        <a class="mt-2 m-auto" href="home">Entrar como invitado</a>
    </form>
</div>
<?php require 'templates/layout/footer.phtml' ?>
