<?php require 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>
<div class="vh-100 d-flex justify-content-center align-items-center">
    <form class="d-flex flex-column w-50 shadow bg-light bg-gradient bg-opacity-75 rounded p-3" method='post' action='login'>
        <h4 class="text-center">Login</h4>
        <div class='form-group mb-2'>
            <label for='username'>User</label>
            <input type='text' class='form-control' id='username' name='username' required>
        </div>
        <div class='form-group mb-2'>
            <label for='password'>Password</label>
            <input type='password' class='form-control' id='password' name='password' required>
        </div>
        <button type='submit' class='btn btn-dark w-50 mt-2 m-auto'>Login</button>
        <a class="mt-2 m-auto text-dark" href="home #home">Enter as a guest</a>
    </form>
</div>
<?php require 'templates/layout/footer.phtml' ?>
