<?php require 'templates/layout/header.phtml' ?>

<div class="container mt-4 d-flex flex-column min-vh-100">
    <div class="header">
        <h1>Genre Management</h1>
        <div class="row">
            <!-- Columna para el formulario -->
            <div class="col-md-4">
                <form class="mb-3">
                    <h3>Add new genre</h3>
                    <label for="name" class="form-label mt-1 mb-auto"><h4>Name</h4></label>
                    <input type="text" class="form-control" id="name" placeholder="Action">

                    <label for="image_url" class="form-label mt-1 mb-auto"><h4>URL de la imagen</h4></label>
                    <input type="url" class="form-control" id="image_url" placeholder="URL">
                    <button class="btn btn-success mt-2">Add genre</button>
                </form>
            </div>

            <!-- Columna para la lista de películas -->
            <div class="col-md-8">
                <div class="genres mt-3">
                    <h3>Genre List</h3> <!-- Agregado encabezado para la lista de películas -->
                    <ul class="list-group mb-4 w-100">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <p class="m-0">Action</p>
                            <span>
                                <button class="btn btn-warning btn-sm">Modify</button>
                                <button class="btn btn-danger btn-sm">Delete</button>
                                <a href="#"><button class="btn btn-dark btn-sm">View movies</button></a>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?php require 'templates/layout/footer.phtml' ?>
</div>
