<?php require 'templates/layout/header.phtml' ?>
<div class="d-flex justify-content-center align-items-center vh-100">
    <div id="carouselExample" class="carousel slide shadow bg-body-tertiary rounded w-75">
        <div class="carousel-inner">
            <?php foreach ($genres as $index => $genre): ?>
                <div class="carousel-item <?= $index == 0 ? 'active' : '' ?>">
                    <a href="genero/<?= $genre->id ?>" class="text-decoration-none">
                        <div class="position-relative text-center">
                            <img src="<?= $genre->image_url ?>" class="d-block w-100 h-100 mx-auto image-genre" alt="<?= $genre->name ?>">
                            <div
                                class="position-absolute top-50 start-50 translate-middle w-100 h-100 d-flex align-items-center justify-content-center overlay">
                                <h3 class="text-white fw-bold fs-1 shadow-text"><?= $genre->name ?></h3>
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach ?>
        </div>

        <!-- Botones de navegación -->
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<?php require 'templates/layout/footer.phtml' ?>
