<?php require 'templates/layout/header.phtml' ?>
    <article class="d-flex flex-column justify-content-center align-items-center vh-100">
        <h1 class="text-bold shadow-text-soft">CINÉPOLIS</h1>
        <p class="lead text-center shadow-text">
            Encontra la mejor información sobre tus peliculas favoritas.
        </p>
        <a href="movies">
            <button type="button" class="btn btn-dark shadow bg-body-tertiary rounded">Ver toda la biblioteca</button>
        </a>
    </article>
<?php require 'templates/layout/footer.phtml' ?>
