<?php require 'templates/layout/header.phtml' ?>
<article class="card mb-3">
    <img src="<?= $movie->image_url ?>" class="card-img-top" alt="<?= $movie->name ?>">
    <div class="card-body shadow bg-body-tertiary rounded">
        <h5 class="card-title"><?= $movie->title ?></h5>
        <p class="card-text"><?= $movie->description ?></p>
        <p class="card-text"><small class="text-body-secondary">Producer: <?= $movie->producer ?></small></p>
        <p class="card-text"><small>Duration: <?= $movie->duration ?></small></p>
        <p class="card-text"><small>Punctuation in IMDb: <?= $movie->punct_imdb ?>/10✮</small></p>
        <p class="card-text"><small>Genre: <?= $genreName ?></small></p>
    </div>
</article>
</main>
<?php require 'templates/layout/footer.phtml' ?>
