<?php require 'templates/layout/header.phtml' ?>

<div class="container mt-4 d-flex flex-column min-vh-100">
    <div class="header">
        <h1>Movie Management</h1>
        <div class="row">
            <!-- Columna para el formulario -->
            <div class="col-md-4">
                <form class="mb-3">
                    <h3>Add new movie</h3>
                    <label for="name" class="form-label mt-1 mb-auto"><h4>Name</h4></label>
                    <input type="text" class="form-control" id="name" placeholder="Terminator">

                    <label for="description" class="form-label mt-1 mb-auto"><h4>Description</h4></label>
                    <input type="text" class="form-control" id="description" placeholder="Movie description">

                    <label for="producer" class="form-label mt-1 mb-auto"><h4>Producer</h4></label>
                    <input type="text" class="form-control" id="producer" placeholder="Christopher Nolan">

                    <label for="duration" class="form-label mt-1 mb-auto"><h4>Duration</h4></label>
                    <input type="text" class="form-control" id="duration" placeholder="120 minutes">

                    <label for="punct_imbd" class="form-label mt-1 mb-auto"><h4>Punction IMDb</h4></label>
                    <input type="number" class="form-control" id="punct_imbd" placeholder="6">

                    <label for="genre" class="form-label mt-1 mb-auto"><h4>Genre</h4></label>
                    <select class="form-select" aria-label="Default select example" id="genre">
                        <option value="1">Action</option>
                    </select>

                    <label for="image_url" class="form-label mt-1 mb-auto"><h4>URL de la imagen</h4></label>
                    <input type="url" class="form-control" id="image_url" placeholder="URL">
                    <button class="btn btn-success mt-2">Add movie</button>
                </form>
            </div>

            <!-- Columna para la lista de películas -->
            <div class="col-md-8">
                <div class="movies mt-3">
                    <h3>Movie List</h3> <!-- Agregado encabezado para la lista de películas -->
                    <ul class="list-group mb-4 w-100">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <p class="m-0">Terminator</p>
                            <span>
                                <button class="btn btn-warning btn-sm">Modify</button>
                                <button class="btn btn-danger btn-sm">Delete</button>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <?php require 'templates/layout/footer.phtml' ?>
</div>
